### ISSUE TITLE
gspread-dataframe doesn't handle '+' signs correctly

### ISSUE THREAD

**Issue by eanxgeek** [robin900/gspread-dataframe#16]
I have an issue, not sure if it is on the get_as_dataframe() or set_as_dataframe(), with a worksheet where one column will hold ('? | '+ | '-).   I suspect it is in the get_as_dataframe().

The gspread-dataframe library has no issue with the question mark however with the plus (+) and minus (-) I have taken steps to ensure that these characters are written as strings, prefixing them with an apostrophe.  When gspread-dataframe does a get_as_dataframe() or a set_as_dataframe() these string characters become non-string characters, instead becoming math operations that result in #ERROR in the worksheet cells.

My program first performs a get_as_dataframe() then appends to that dataframe and then does a set_as_dataframe().  I suspect the issue is actually in the get_as_dataframe() because the newly appended dataframe items are written out to the worksheet correctly.

**Comment by eanxgeek** [comment]
BTW, I have found that a simple updated_df.replace("+", "'+", inplace=True) will work as an easy workaround.

**Comment by robin900** [comment]
Sorry for the delay in responding. I have written a local test using a Google sheet, with cells having a value `'+` or `'-`. The `get_as_dataframe()` call, with no arguments except the Worksheet object, produces a DataFrame with the cell values intact.

The problem is with the interaction of `set_with_dataframe` and the Sheets API. The Sheets API treats any `'` at the start of a cell value to indicate that the remainder of the value is a string literal and should not be interpreted as a formula for anything else.

The solution is to change the code in `gspread_dataframe` to prepend a `'` character not only when allow_formulae=False and a cell value begins with `=`, but also when a cell value begins with `'`.

I have created test coverage (including intergration test) that confirms the above solution is correct and produces no regressions. I am about to produce a 3.0.3 release containing the fix.
