### ISSUE TITLE
Sheets API erroneously rejects new rowCount if (new rowCount * old columnCount) > 5000000 (was: Bug in the number of cells of the dataframe

### ISSUE THREAD

**Issue by devironl** [robin900/gspread-dataframe#37]
Hello

I am trying to add 2 dataframes to a Google sheet (in separate tabs) by using the `set_with_dataframe` function
 
Here are the shapes of those dataframes:
`(41967, 14)
(200000, 4)`

This gives 1.387.000 cells in total.

However I get the following error: 

`Traceback (most recent call last):
  File "dynamo_to_google_sheet.py", line 144, in <module>
    set_with_dataframe(output_sheet, df)
  File "venv/lib/python3.8/site-packages/gspread_dataframe.py", line 247, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "venv/lib/python3.8/site-packages/gspread_dataframe.py", line 108, in _resize_to_minimum
    worksheet.resize(rows, cols)
  File "venv/lib/python3.8/site-packages/gspread/models.py", line 1272, in resize
    return self.spreadsheet.batch_update(body)
  File "venv/lib/python3.8/site-packages/gspread/models.py", line 145, in batch_update
    r = self.client.request(
  File "venv/lib/python3.8/site-packages/gspread/client.py", line 73, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].updateSheetProperties: This action would increase the number of cells in the workbook above the limit of 5000000 cells.', 'status': 'INVALID_ARGUMENT'}`

Since my dataframe sizes does not reach the quota I think the error message is misleading. Are there other limitations or Am I doing something wrong ?

Thanks for your help !

**Comment by devironl** [comment]
I was finally able to fix this by pre-defining the number of rows and colons of the sheets before setting the dataframe

```
output_sheet = client.open("sheet_name").add_worksheet(sheet_name, df.shape[0], df.shape[1])
set_with_dataframe(output_sheet, df, resize=True)
```

I hope this post will help someone else !

**Comment by robin900** [comment]
@devironl So I discovered the cause of your initially reported bug: If you submit to the Sheets API a request to change both a worksheet's rowCount _and_ columnCount, the Sheets API does the following:

1. Using the new `rowCount` value and the _existing_ `columnCount` value, calculates whether `rowCount * columnCount > 5000000`. If the cell count limit is exceeded, a 400 response is returned.
2. Using the new `rowCount` and new `columnCount` values, calculate whether `rowCount * columnCount > 5000000`. If the cell count limit is exceeded, a 400 response is returned.
3. Otherwise, apply the changes to rowCount and columnCount and return a 200 response.

Your particular case -- of wanting rows=200000 and cols=2 for a worksheet with the default size of rows=100, cols=26 -- caused step 1 to return a 400 response.

I am working on a pull request that addresses this case, by calling worksheet.resize() separately for columnCount and then again for rowCount. I'll add you as a reviewer when it's done.

**Comment by robin900** [comment]
@devironl Sorry, can't add you as a reviewer to PR, but there is full test coverage on the new code and I'll be making a new PyPI release in about 30 min.

**Comment by robin900** [comment]
@devironl Release 3.2.1 is [now in PyPI](https://pypi.org/project/gspread-dataframe/3.2.1/).
