### ISSUE TITLE
Feature Request: Append feature to an existing sheet.

### ISSUE THREAD

**Issue by pomcho555** [robin900/gspread-dataframe#50]
Hi!
I frequently use this library. Thanks to you and this library, I smoothly work well.

And I've had so many use-case that needs to append feature for a manually updated existing sheet. I implemented this feature from scratch using [this original gspread feature](https://docs.gspread.org/en/latest/user-guide.html#getting-all-values-from-a-worksheet-as-a-list-of-lists). But I believe sorta "append" feature could help many engineer's works.

## The way to implement
1. Create a feature searching last row(at the end of line), this could be low level API for a next step and others
2. Implement append feature using above `1` feature.

If you think this doesn't cause inconsistency against the existing code. I'd love to introduce it!

**Comment by motin** [comment]
This should be possible already, but isn't due to a bug.

One should be able to append to an existing sheet by using the `row` argument to `set_with_dataframe`: https://github.com/robin900/gspread-dataframe/blob/f51dfa4bc816e4c2fb17aa4c3523e3972a8695dc/gspread_dataframe.py#L225

Setting it to the number of worksheet rows + 1 ought to make the dataframe be appended at the end. 

Unfortunately, the resize-logic at https://github.com/robin900/gspread-dataframe/blob/f51dfa4bc816e4c2fb17aa4c3523e3972a8695dc/gspread_dataframe.py#L276-L279 does not take the row and col arguments into consideration, so the append fails with a `Range exceeds grid limits` error.

Patch that makes it work available in https://github.com/robin900/gspread-dataframe/pull/51
